version: '3'

services:

    db:
        image: postgres:9.4
        environment:
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./dbdata:/var/lib/postgresql/data

    server:
        image: server:compose
        build: ./server
        environment:
            DB_HOST: db 
            DB_PORT: 5432
            DB_DATABASE: hireranked_prod
            DB_USERNAME: postgres 
            DB_PASSWORD: postgres
        ports:
            - "5000:5000"
        volumes:
            - ./server/server.js:/usr/src/app/server.js 
            - ./server/config:/usr/src/app/config 
            - ./server/routes:/usr/src/app/routes 
            - ./server/validation:/usr/src/app/validation
        links:
            - db

    client:
        image: client:compose
        build: ./client
        ports:
            - "3000:3000"
        links:
            - server

      